Take long time to calculate the gradients of whole datasets, so divide them into chunks
<br>Pytorch can do batch iteration and calculation. It has its builtin dataloader function
<br> - epoch=1 forward and backward pass of ALL trainng samples
<br> - batch_size=number of trainng samples in one forwrd and backward pass
<br> - number of iterations= number of passes, each pass using batch size number of samples
<br> - eg. 100 samples, batch_size=20 --> 100/20 = 5 iteration for 1 epoch

In [21]:
import torch 
import torchvision
from torch.utils.data import Dataset, DataLoader
import numpy as np
import math

In [22]:
class WineDataset(Dataset):
    def __init__(self):
        #data loading
        xy=np.loadtxt('Dataset/wine.csv',delimiter=",",dtype=np.float32,skiprows=1)
        self.x=xy[:,1:]
        self.y=xy[:,[0]] 
        #n_samples,1
        self.n_samples=xy.shape[0]
    def __getitem__(self,index):
        #allow indexing later, dataset[0]
        return self.x[index],self.y[index]
    def __len__(self):
        #this will allow len of 
        return self.n_samples

In [23]:
dataset=WineDataset()

In [24]:
first_dataset=dataset[0]
features,labels=first_dataset
features

array([1.423e+01, 1.710e+00, 2.430e+00, 1.560e+01, 1.270e+02, 2.800e+00,
       3.060e+00, 2.800e-01, 2.290e+00, 5.640e+00, 1.040e+00, 3.920e+00,
       1.065e+03], dtype=float32)

In [25]:
labels

array([1.], dtype=float32)

In [28]:
dataloader=DataLoader(dataset=dataset,batch_size=4,shuffle=True)

In [29]:
dataiter=iter(dataloader)
data=next(dataiter)
features,labels=data
features

tensor([[1.3680e+01, 1.8300e+00, 2.3600e+00, 1.7200e+01, 1.0400e+02, 2.4200e+00,
         2.6900e+00, 4.2000e-01, 1.9700e+00, 3.8400e+00, 1.2300e+00, 2.8700e+00,
         9.9000e+02],
        [1.2770e+01, 2.3900e+00, 2.2800e+00, 1.9500e+01, 8.6000e+01, 1.3900e+00,
         5.1000e-01, 4.8000e-01, 6.4000e-01, 9.9000e+00, 5.7000e-01, 1.6300e+00,
         4.7000e+02],
        [1.2370e+01, 1.2100e+00, 2.5600e+00, 1.8100e+01, 9.8000e+01, 2.4200e+00,
         2.6500e+00, 3.7000e-01, 2.0800e+00, 4.6000e+00, 1.1900e+00, 2.3000e+00,
         6.7800e+02],
        [1.3690e+01, 3.2600e+00, 2.5400e+00, 2.0000e+01, 1.0700e+02, 1.8300e+00,
         5.6000e-01, 5.0000e-01, 8.0000e-01, 5.8800e+00, 9.6000e-01, 1.8200e+00,
         6.8000e+02]])

In [30]:
labels

tensor([[1.],
        [3.],
        [2.],
        [3.]])

Training Loop

In [36]:
num_epochs=2

In [38]:
total_samples=len(dataset)
total_samples

178

In [45]:
n_iterations=math.ceil(total_samples/4)
n_iterations

45

In [47]:
for epoch in range(num_epochs):
    for i,(inputs,labels) in enumerate(dataloader):
        #forward  backward and pass
        if (i+1)%5==0:
            print(f'epoch { epoch +1 }/{num_epochs},step { i +1 }/{n_iterations} , inputs {inputs.shape}')

epoch 1/2,step 5/45 , inputs torch.Size([4, 13])
epoch 1/2,step 10/45 , inputs torch.Size([4, 13])
epoch 1/2,step 15/45 , inputs torch.Size([4, 13])
epoch 1/2,step 20/45 , inputs torch.Size([4, 13])
epoch 1/2,step 25/45 , inputs torch.Size([4, 13])
epoch 1/2,step 30/45 , inputs torch.Size([4, 13])
epoch 1/2,step 35/45 , inputs torch.Size([4, 13])
epoch 1/2,step 40/45 , inputs torch.Size([4, 13])
epoch 1/2,step 45/45 , inputs torch.Size([2, 13])
epoch 2/2,step 5/45 , inputs torch.Size([4, 13])
epoch 2/2,step 10/45 , inputs torch.Size([4, 13])
epoch 2/2,step 15/45 , inputs torch.Size([4, 13])
epoch 2/2,step 20/45 , inputs torch.Size([4, 13])
epoch 2/2,step 25/45 , inputs torch.Size([4, 13])
epoch 2/2,step 30/45 , inputs torch.Size([4, 13])
epoch 2/2,step 35/45 , inputs torch.Size([4, 13])
epoch 2/2,step 40/45 , inputs torch.Size([4, 13])
epoch 2/2,step 45/45 , inputs torch.Size([2, 13])
