In [1]:
import torch
import torch.nn as nn
import numpy as np

In [2]:
def softmax(x):
    return np.exp(x)/np.sum(np.exp(x),axis=0)

In [3]:
x=np.array([2.0,1.0,0.1])
outputs=softmax(x)
print('softmax numpy:',outputs)

softmax numpy: [0.65900114 0.24243297 0.09856589]


In [5]:
x=torch.tensor([2.0,1.0,0.1])
outputs=torch.softmax(x,dim=0)
outputs

tensor([0.6590, 0.2424, 0.0986])

Lots of time softmax is combined with cross entropy loss
<br> used for calssification


In [14]:
def cross_entropy(actual,predicted):
    loss=np.sum(actual * np.log(predicted))
    return loss

y must be one hot encoded
<br> if class 0: [1 0 0 ]
<br> if class 1: [0 1 0]
<br> if class 2: [0 0 1]

In [15]:
Y=np.array([1,0,0])

In [16]:
y_pred_good=np.array([0.7,0.2,0.1])
y_pred_bad=np.array([0.1,0.3,0.6])

In [17]:
l1=cross_entropy(Y,y_pred_good)
l2=cross_entropy(Y,y_pred_bad)

In [18]:
print("Good Predition",l1)
print("Bad prediction",l2)

Good Predition -0.35667494393873245
Bad prediction -2.3025850929940455


In [31]:
loss=nn.CrossEntropyLoss()

In [32]:
Y=torch.tensor([0])
#number of samples * nclasses=1*3

In [33]:
y_pred_good=torch.tensor([[0.7,0.2,0.1]])

In [40]:
y_pred_bad=torch.tensor([[0.3,0.6,0.1]])

In [41]:
l1=loss(y_pred_good,Y)
l2=loss(y_pred_bad,Y)


In [42]:
print(f'good loss: {l1:.3f}')
print(f'bad loss: {l2:.3f}')

good loss: 0.274
bad loss: 1.153


In [48]:
_,predictions1=torch.max(y_pred_good,axis=1)
_,predictions2=torch.max(y_pred_bad,axis=1)

In [49]:
predictions1

tensor([0])

In [50]:
predictions2

tensor([1])

In [51]:
#samples
Y=torch.tensor([2,0,1])

In [52]:
y_pred_good=torch.tensor([[0,0,1.0],[0.8,0.1,0.1],[0.2,0.7,0.1]])

In [53]:
y_pred_bad=torch.tensor([[0,1.0,0],[0.1,0.8,0.1],[0.7,0.2,0.1]])

In [54]:
l1=loss(y_pred_good,Y)
l2=loss(y_pred_bad,Y)

In [55]:
l1

tensor(0.6697)

In [56]:
l2

tensor(1.4030)

In [57]:
_,predictions1=torch.max(y_pred_good,axis=1)
_,predictions2=torch.max(y_pred_bad,axis=1)

In [58]:
predictions1

tensor([2, 0, 1])

In [59]:
predictions2

tensor([1, 1, 0])

In [61]:
class NeuralNet2(nn.Module):
    def __init__(self,input_size,hidden_size,num_classes):
        super(NeuralNet2,self).__init__()
        self.linear=nn.Linear(input_size,hidden_size)
        self.relu=nn.ReLU()
        self.linear2=nn.Linear(hidden_size,num_classes)
    def forward(self,x):
        out=self.linear(x)
        out=self.relu(out)
        out=self.linear2(out)
        return out

In [62]:
model=NeuralNet2(input_size=28*28,hidden_size=5,num_classes=3)
criterion=nn.CrossEntropyLoss()