In [ ]:
import torch

In [ ]:
import torch.nn as nn

In [12]:
class Model(nn.Module):
    def __init__(self,n_input_features):
        super(Model,self).__init__()
        self.linear=nn.Linear(n_input_features,1)
    def forward(self,x):
        y_pred=torch.sigmoid(self.linear(x))
        return y_pred

In [33]:
model=Model(n_input_features=6)

In [31]:
learning_rate=0.01
optimizer=torch.optim.SGD(model.parameters(),lr=learning_rate)

In [34]:
print(optimizer.state_dict())

{'state': {}, 'param_groups': [{'lr': 0.01, 'momentum': 0, 'dampening': 0, 'weight_decay': 0, 'nesterov': False, 'maximize': False, 'foreach': None, 'differentiable': False, 'params': [0, 1]}]}


In [35]:
checkpoint={
    "epoch":90,
    "model_state":model.state_dict(),
    "optimizer_state":optimizer.state_dict()
}

In [37]:
torch.save(checkpoint,"checkpoint.pth")

In [39]:
loaded_checkpoint=torch.load("checkpoint.pth")
epoch=loaded_checkpoint['epoch']
model=Model(n_input_features=6)
optimizer=torch.optim.SGD(model.parameters(),lr=0)
model.load_state_dict(checkpoint["model_state"])
optimizer.load_state_dict(checkpoint['optimizer_state'])

In [40]:
print(optimizer.state_dict())

{'state': {}, 'param_groups': [{'lr': 0.01, 'momentum': 0, 'dampening': 0, 'weight_decay': 0, 'nesterov': False, 'maximize': False, 'foreach': None, 'differentiable': False, 'params': [0, 1]}]}


Model Parameters before saving

In [24]:
for params in model.parameters():
    print(params)

Parameter containing:
tensor([[-0.3614, -0.0571, -0.2374,  0.2131,  0.1111,  0.1269]],
       requires_grad=True)
Parameter containing:
tensor([-0.3424], requires_grad=True)


In [25]:
FILE="model.pth"


In [26]:
torch.save(model.state_dict(),FILE)

In [27]:
loaded_model=Model(n_input_features=6)
loaded_model.load_state_dict(torch.load(FILE))
loaded_model.eval()

Model(
  (linear): Linear(in_features=6, out_features=1, bias=True)
)

In [29]:
for param in loaded_model.parameters():
    print(param)

Parameter containing:
tensor([[-0.3614, -0.0571, -0.2374,  0.2131,  0.1111,  0.1269]],
       requires_grad=True)
Parameter containing:
tensor([-0.3424], requires_grad=True)


In [17]:
#torch.save(model,FILE) #This uses pickle module

In [19]:
model=torch.load(FILE)
model.eval()

Model(
  (linear): Linear(in_features=6, out_features=1, bias=True)
)

In [20]:
for params in model.parameters():
    print(params)

Parameter containing:
tensor([[ 0.2601,  0.3471, -0.0335, -0.0770, -0.1125, -0.0730]],
       requires_grad=True)
Parameter containing:
tensor([-0.1270], requires_grad=True)


In [9]:
## STATE DICT ##

In [ ]:
torch.save(model.state_dict(),PATH)
model=Model(*args,**kwargs)
model.load_state_dict(torch.load(PATH))
model.eval()

While saving the model to gpu, while loading in cpu, use
load_state_dict(map_location=device)