In [1]:
import torch

Basic Mathematical Operation

In [25]:
x=torch.empty(3)
x

tensor([2.3694e-38, 8.2485e-01, 8.9776e-01])

In [26]:
x2=torch.empty(2,3)
x2

tensor([[-1.1903e+21,  1.0874e-42,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00]])

In [6]:
xrand=torch.rand(2,2)
xrand

tensor([[0.9804, 0.9894],
        [0.4910, 0.4021]])

In [15]:
x=torch.tensor([1,2,3])
x.size()

torch.Size([3])

In [27]:
x=torch.rand(2,2)
y=torch.rand(2,2)
print(x)
print(y)
z=x+y
z

tensor([[0.5493, 0.7122],
        [0.7247, 0.3393]])
tensor([[0.0752, 0.8501],
        [0.5593, 0.8980]])


tensor([[0.6245, 1.5623],
        [1.2840, 1.2372]])

In [18]:
z_add=torch.add(x,y)
z_add

tensor([[0.6581, 1.7113],
        [1.7907, 1.5957]])

Inplace operation contains _

In [20]:
y.add_(z)
y

tensor([[0.8470, 2.5978],
        [2.6836, 2.2217]])

In [21]:
z=x-y
z

tensor([[-0.3778, -1.7729],
        [-1.7858, -1.2518]])

In [22]:
z=torch.sub(x,y)
z

tensor([[-0.3778, -1.7729],
        [-1.7858, -1.2518]])

In [23]:
z=torch.mul(x,y)
z

tensor([[0.3974, 2.1428],
        [2.4092, 2.1546]])

In [29]:
z=torch.div(x,y)
z

tensor([[7.3061, 0.8378],
        [1.2956, 0.3779]])

Slicing Operation


In [30]:
x=torch.rand(5,3)
x

tensor([[0.4024, 0.4257, 0.9915],
        [0.2914, 0.3028, 0.6991],
        [0.7937, 0.6925, 0.6446],
        [0.0115, 0.6675, 0.6452],
        [0.8456, 0.1093, 0.8351]])

In [32]:
x[1,:]

tensor([0.2914, 0.3028, 0.6991])

In [33]:
x[1,1]

tensor(0.3028)

In [34]:
x[:,1]

tensor([0.4257, 0.3028, 0.6925, 0.6675, 0.1093])

.item(gets the actual value of tensor)

In [35]:
x[1,1].item()

0.3027995228767395

In [36]:
x=torch.rand(4,4)
print(x)
y=x.view(16)
y

tensor([[0.6951, 0.4433, 0.4479, 0.6506],
        [0.6195, 0.6312, 0.1111, 0.7321],
        [0.8492, 0.9812, 0.7944, 0.4864],
        [0.3099, 0.7634, 0.0736, 0.5205]])


tensor([0.6951, 0.4433, 0.4479, 0.6506, 0.6195, 0.6312, 0.1111, 0.7321, 0.8492,
        0.9812, 0.7944, 0.4864, 0.3099, 0.7634, 0.0736, 0.5205])

In [37]:
y=x.view(-1,8)
y

tensor([[0.6951, 0.4433, 0.4479, 0.6506, 0.6195, 0.6312, 0.1111, 0.7321],
        [0.8492, 0.9812, 0.7944, 0.4864, 0.3099, 0.7634, 0.0736, 0.5205]])

In [38]:
y.size()

torch.Size([2, 8])

In [39]:
y=x.view(2,8)
y

tensor([[0.6951, 0.4433, 0.4479, 0.6506, 0.6195, 0.6312, 0.1111, 0.7321],
        [0.8492, 0.9812, 0.7944, 0.4864, 0.3099, 0.7634, 0.0736, 0.5205]])

converting to numpy to tensor and vice-vers

In [40]:
import numpy as np

In [42]:
a=torch.ones(5)
a

tensor([1., 1., 1., 1., 1.])

In [43]:
b=a.numpy()
b

array([1., 1., 1., 1., 1.], dtype=float32)

In [44]:
a.add_(1)
a

tensor([2., 2., 2., 2., 2.])

In [45]:
b

array([2., 2., 2., 2., 2.], dtype=float32)

When changing the tensor to numpy, on changes tensor, it also change to numpy

In [48]:
a=np.ones(1)
a

array([1.])

In [49]:
b=torch.from_numpy(a)
b

tensor([1.], dtype=torch.float64)

In [50]:
a+=1
a

array([2.])

In [51]:
b

tensor([2.], dtype=torch.float64)

In [52]:
if torch.cuda.is_available():
    device=torch.device("cuda")
    x=torch.ones(5,device=device)
    y=torch.ones(5)
    y=y.to(device)
    z=x*y
    z=z.to("cpu")

Changing to cuda, calcuates or operates faster than cpu
so the tensor are transferred to cuda for operation but numpy only operates or works in the cpu so if we want to change the values back to numpy we must first convert the device to cpu for it to work

In [55]:
x=torch.ones(5,requires_grad=True)
x

tensor([1., 1., 1., 1., 1.], requires_grad=True)

This tell that later in the code, it needs to calculate the gardient of this variab