In [1]:
import torch

In [3]:
x=torch.rand(3,requires_grad=True)
x

tensor([0.7303, 0.3350, 0.7863], requires_grad=True)

<br>This creates the computation graph
<br>x >
<br> &ensp; &ensp;   y
<br>2 >

<br>This creates the functions automatically that would be used for the backpropagation
- Whenever we want to calcuate the gradients we must specify requires_gard
- We can simply calculate it by calling backward()

In [4]:
y=x+2
y

tensor([2.7303, 2.3350, 2.7863], grad_fn=<AddBackward0>)

In [5]:
z=y*y*2
z

tensor([14.9095, 10.9044, 15.5273], grad_fn=<MulBackward0>)

It must be scalar

In [27]:
z=z.mean()
z

tensor(13.7804, grad_fn=<MeanBackward0>)

z.backward()=dz/dx

In [7]:
z.backward()
x.grad

tensor([3.6405, 3.1133, 3.7151])

Vector Chekoviam Product



To remove tracking of gradiants:
<br> x.requires_grad_(False)
<br> x.detach()
<br> with torch.no_grad()

In [10]:
x.requires_grad_(False)
x

tensor([0.7303, 0.3350, 0.7863])

In [11]:
y=x.detach()
y

tensor([0.7303, 0.3350, 0.7863])

In [12]:
with torch.no_grad():
    y=x+2
    print(y)

tensor([2.7303, 2.3350, 2.7863])


The gard values get accumulated so we must empty the gardient. It affects the optimization process. <br> By adding the grad.zero_() to the ones whose gardient we are going to calculate

In [25]:
weights=torch.ones(4,requires_grad=True)


In [23]:
for epoch in range(4):
    model_Output=(weights*3).sum()
    model_Output.backward()
    print(weights.grad)
    weights.grad.zero_()

tensor([9., 9., 9., 9.])
tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])


In [26]:
optimizer=torch.optim.SGD(weights,lr=0.01)
optimizer.step()
optimizer.zero_grad()

TypeError: params argument given to the optimizer should be an iterable of Tensors or dicts, but got torch.FloatTensor